interface subregionType {
  name: string,
  key: string,
  color: string,
  shape?: React.ReactNode,
  text: {
    x: number,
    y: number,
    el: React.ReactNode,
  },
  zoom: {
    x: number,
    y: number,
    amount: React.ReactNode,
  },
}

export const subregions: subregionType = [
  {
    name: "North Africa",
    id: "AFNO",
    color: "#fb9a96",
    text: { x: 49.5, y: 39, el: <>North Africa</>, },
    zoom: { x: 62, y: 37, amount: 3.5, },
  },
  {
    name: "East Africa",
    id: "AFEA",
    color: "#fdbb86",
    text: { x: 59, y: 50, el: <>East<br/>Africa</>, },
    zoom: { x: 74, y: 65, amount: 3, },
  },
  {
    name: "Southern Africa",
    id: "AFSO",
    color: "#9970ac",
    text: { x: 54, y: 69, el: <>Southern<br/>Africa</>, },
    zoom: { x: 66, y: 78, amount: 4, },
  },
  {
    name: "Central Africa",
    id: "AFCE",
    color: "#7fcdba",
    text: { x: 53.5, y: 54, el: <>Central<br/>Africa</>, },
    zoom: { x: 63, y: 59, amount: 4.5, },
  },
  {
    name: "West Africa",
    id: "AFWE",
    color: "#ffeda2",
    text: { x: 46.4, y: 48.3, el: <>West Africa</>, },
    zoom: { x: 56, y: 48.3, amount: 4, },
  },
  {
    name: "Northern North America",
    id: "AMNO",
    color: "#9970aa",
    text: { x: 23, y: 10, el: <>Northern N. Am.</>, },
    zoom: { x: 28, y: 0, amount: 2, },
  },
  {
    name: "Eastern North America",
    id: "AMEA",
    color: "#7fcdbd",
    text: { x: 26.5, y: 27.5, el: <>Eastern<br/>N. Am.</>, },
    zoom: { x: 30, y: 22, amount: 4, },
  },
  {
    name: "Southwest North America",
    id: "AMSW",
    color: "#ffeda5",
    text: { x: 17.8, y: 30.5, el: <>Southwest<br/>N. Am.</>, },
    zoom: { x: 19.5, y: 30.5, amount: 5, },
  },
  {
    name: "Northwest North America",
    id: "AMNW",
    color: "#80b1d5",
    text: { x: 17, y: 17, el: <>Northwest<br/>N. Am.</>, },
    zoom: { x: 18, y: 16, amount: 5.5, },
  },
  {
    name: "Interior North America",
    id: "AMIN",
    color: "#fb9a93",
    text: { x: 22.5, y: 21, el: <>Interior<br/>N. Am.</>, },
    zoom: { x: 24, y: 17, amount: 4.5, },
  },
  {
    name: "Central America",
    id: "AMCE",
    color: "#fdbb82",
    text: { x: 21, y: 42, el: <>Central<br/>America</>, },
    zoom: { x: 23, y: 44, amount: 4.7, },
  },
  {
    name: "Caribbean",
    id: "AMCR",
    color: "#fb9a94",
    text: { x: 28, y: 42, el: <>Caribbean</>, },
    zoom: { x: 30, y: 43, amount: 5.5, },
  },
  {
    name: "Highland South America",
    id: "AMHI",
    color: "#ffeda3",
    text: { x: 26, y: 61, el: <>Highland<br/>S. Am.</>, },
    zoom: { x: 29, y: 73.5, amount: 2.8, },
  },
  {
    name: "Lowland South America",
    id: "AMLO",
    color: "#80b1d1",
    text: { x: 32, y: 59, el: <>Lowland<br/>S. Am.</>, },
    zoom: { x: 36, y: 67, amount: 3.5, },
  },
  {
    name: "Southern South America",
    id: "AMSO",
    color: "#fb9a95",
    text: { x: 32, y: 79, el: <>Southern<br/>S. Am.</>, },
    zoom: { x: 36, y: 95, amount: 3.7, },
  },
  {
    name: "North Asia",
    id: "ASNO",
    color: "#80b1d3",
    text: { x: 71, y: 11, el: <>North Asia</>, },
    zoom: { x: 110, y: 5, amount: 2.25, },
  },
  {
    name: "East Asia",
    id: "ASEA",
    color: "#fdbb84",
    text: { x: 79, y: 34, el: <>East Asia</>, },
    zoom: { x: 96.5, y: 30, amount: 4, },
  },
  {
    name: "Southeast Asia",
    id: "ASSE",
    color: "#ffeda0",
    text: { x: 78, y: 48, el: <>Southeast<br/>Asia</>, },
    zoom: { x: 101, y: 51, amount: 3.5, },
  },
  {
    name: "Highland Asia",
    id: "ASHI",
    color: "#fb9a99",
    text: { x: 71.3, y: 31, el: <>Highland<br/>Asia</>, },
    zoom: { x: 84, y: 31, amount: 5, },
  },
  {
    name: "South Asia",
    id: "ASSO",
    color: "#9970ab",
    text: { x: 69, y: 38, el: <>South<br/>Asia</>, },
    zoom: { x: 84, y: 38.5, amount: 4, },
  },
  {
    name: "West Asia",
    id: "ASWE",
    color: "#80b1d2",
    text: { x: 61, y: 34, el: <>West<br/>Asia</>, },
    zoom: { x: 72.2, y: 34, amount: 4, },
  },
  {
    name: "Central Asia",
    id: "ASCE",
    color: "#7fcdbb",
    text: { x: 64.6, y: 24.3, el: <>Central Asia</>, },
    zoom: { x: 79.3, y: 18.5, amount: 4.2, },
  },
  {
    name: "Inner Asia",
    id: "ASIN",
    color: "#ffeda4",
    text: { x: 74.5, y: 22, el: <>Inner Asia</>, },
    zoom: { x: 91.5, y: 16.5, amount: 4.2, },
  },
  {
    name: "Eastern Europe",
    id: "EUEA",
    color: "#ffeda1",
    text: { x: 56.5, y: 16, el: <>Eastern<br/>Europe</>, },
    zoom: { x: 69, y: 6.5, amount: 3.5, },
  },
  {
    name: "Western Europe",
    id: "EUWE",
    color: "#fdbb85",
    text: { x: 48, y: 20, el: <>Western<br/>Europe</>, },
    zoom: { x: 57, y: 12.5, amount: 4, },
  },
  {
    name: "Australia",
    id: "OCAU",
    color: "#fdbb83",
    text: { x: 83.7, y: 73.5, el: <>Australia</>, },
    zoom: { x: 104, y: 85, amount: 4, },
  },
  {
    name: "Madagascar",
    id: "OCMD",
    color: "#fb9a97",
    text: { x: 61, y: 68, el: <>Madagascar</>, },
    zoom: { x: 70.5, y: 76, amount: 5, },
  },
  {
    name: "Melanesia",
    id: "OCML",
    color: "#fb9a98",
    shape: <path d="M 86,23.5 98,25 99.5,31 94.5,33 92,29 85,28 z" fill="#808080"></path>,
    text: { x: 87, y: 59, el: <>Melanesia</>, },
    zoom: { x: 112, y: 69, amount: 4, },
  },
  {
    name: "Micronesia",
    id: "OCMC",
    color: "#80b1d4",
    shape: <path d="M 86,23.5 89,19 98,21 98,25 z" fill="#808080"></path>,
    text: { x: 90, y: 48, el: <>Micronesia</>, },
    zoom: { x: 110, y: 52, amount: 4.5, },
  },
  {
    name: "Polynesia",
    id: "OCPL",
    color: "#7fcdbc",
    shape: <path d="M 88,42.5 100,40 100,23 98,25 99.5,31 94.5,33 z M 0,41 22,34.2 7.5,17 0,23 z" fill="#808080"></path>,
    text: { x: 3, y: 50, el: <>Polynesia</>, },
    zoom: { x: 2, y: 63, amount: 2.5, },
  },
];
