interface subregionType {
  name: string,
  id: string,
  color: string,
  shape?: React.ReactNode,
  neighbors: string[],
  description: string,
  text: {
    x: number,
    y: number,
    el: React.ReactNode,
  },
  zoom: {
    x: number,
    y: number,
    amount: number,
  },
}

export const subregions: subregionType[] = [
  {
    name: "North Africa",
    id: "AFNO",
    color: "#fb9a96",
    neighbors: ['EUWE','ASWE','AFWE'],
    description: ``,
    text: { x: 49.5, y: 39, el: <>North Africa</>, },
    zoom: { x: 62, y: 37, amount: 3.5, },
  },
  {
    name: "East Africa",
    id: "AFEA",
    color: "#fdbb86",
    neighbors: ['ASWE','AFNO','AFCE','OCMD'],
    description: ``,
    text: { x: 59, y: 50, el: <>East<br/>Africa</>, },
    zoom: { x: 74, y: 65, amount: 3, },
  },
  {
    name: "Southern Africa",
    id: "AFSO",
    color: "#9970ac",
    neighbors: ['AFEA','AFCE'],
    description: ``,
    text: { x: 54, y: 69, el: <>Southern<br/>Africa</>, },
    zoom: { x: 66, y: 78, amount: 4, },
  },
  {
    name: "Central Africa",
    id: "AFCE",
    color: "#7fcdba",
    neighbors: ['AFWE','AFEA'],
    description: ``,
    text: { x: 53.5, y: 54, el: <>Central<br/>Africa</>, },
    zoom: { x: 63, y: 59, amount: 4.5, },
  },
  {
    name: "West Africa",
    id: "AFWE",
    color: "#ffeda2",
    neighbors: ['AFNO','AFCE'],
    description: ``,
    text: { x: 46.4, y: 48.3, el: <>West Africa</>, },
    zoom: { x: 56, y: 48.3, amount: 4, },
  },
  {
    name: "Northern North America",
    id: "AMNO",
    color: "#9970aa",
    neighbors: ['ASNO','AMNW','AMEA','AMIN'],
    description: ``,
    text: { x: 23, y: 10, el: <>Northern N. Am.</>, },
    zoom: { x: 28, y: 0, amount: 2, },
  },
  {
    name: "Eastern North America",
    id: "AMEA",
    color: "#7fcdbd",
    neighbors: ['AMNO','AMIN','AMSW'],
    description: `Largely coterminous with the Eastern Woodlands, this subregion accounts for the cultural areas of the Northeastern Woodlands, Southeastern Woodlands, and Great Lakes, including language families like the Algonquian, Iroquoian, and Muskogean.`,
    text: { x: 26.5, y: 27.5, el: <>Eastern<br/>N. Am.</>, },
    zoom: { x: 30, y: 22, amount: 4, },
  },
  {
    name: "Southwest North America",
    id: "AMSW",
    color: "#ffeda5",
    neighbors: ['AMCE','AMIN'],
    description: ``,
    text: { x: 17.8, y: 30.5, el: <>Southwest<br/>N. Am.</>, },
    zoom: { x: 19.5, y: 30.5, amount: 5, },
  },
  {
    name: "Northwest North America",
    id: "AMNW",
    color: "#80b1d5",
    neighbors: ['AMNO','AMIN'],
    description: ``,
    text: { x: 17, y: 17, el: <>Northwest<br/>N. Am.</>, },
    zoom: { x: 18, y: 16, amount: 5.5, },
  },
  {
    name: "Interior North America",
    id: "AMIN",
    color: "#fb9a93",
    neighbors: ['AMEA','AMNW','AMSW'],
    description: ``,
    text: { x: 22.5, y: 21, el: <>Interior<br/>N. Am.</>, },
    zoom: { x: 24, y: 17, amount: 4.5, },
  },
  {
    name: "Central America",
    id: "AMCE",
    color: "#fdbb82",
    neighbors: ['AMSW','AMCR'],
    description: ``,
    text: { x: 21, y: 42, el: <>Central<br/>America</>, },
    zoom: { x: 23, y: 44, amount: 4.7, },
  },
  {
    name: "Caribbean",
    id: "AMCR",
    color: "#fb9a94",
    neighbors: ['AMLO','AMCE'],
    description: ``,
    text: { x: 28, y: 42, el: <>Caribbean</>, },
    zoom: { x: 30, y: 43, amount: 5.5, },
  },
  {
    name: "Highland South America",
    id: "AMHI",
    color: "#ffeda3",
    neighbors: ['AMLO','AMSO'],
    description: ``,
    text: { x: 26, y: 61, el: <>Highland<br/>S. Am.</>, },
    zoom: { x: 29, y: 73.5, amount: 2.8, },
  },
  {
    name: "Lowland South America",
    id: "AMLO",
    color: "#80b1d1",
    neighbors: ['AMCR','AMSO','AMHI'],
    description: ``,
    text: { x: 32, y: 59, el: <>Lowland<br/>S. Am.</>, },
    zoom: { x: 36, y: 67, amount: 3.5, },
  },
  {
    name: "Southern South America",
    id: "AMSO",
    color: "#fb9a95",
    neighbors: ['AMLO','AMHI'],
    description: ``,
    text: { x: 32, y: 79, el: <>Southern<br/>S. Am.</>, },
    zoom: { x: 36, y: 96.5, amount: 3.7, },
  },
  {
    name: "North Asia",
    id: "ASNO",
    color: "#80b1d3",
    neighbors: ['AMNO','EUEA','ASIN','ASCE'],
    description: ``,
    text: { x: 71, y: 11.2, el: <>North Asia</>, },
    zoom: { x: 110, y: 5, amount: 2.25, },
  },
  {
    name: "East Asia",
    id: "ASEA",
    color: "#fdbb84",
    neighbors: ['ASIN','ASHI','ASSE'],
    description: ``,
    text: { x: 79, y: 34, el: <>East Asia</>, },
    zoom: { x: 96.5, y: 30, amount: 4, },
  },
  {
    name: "Southeast Asia",
    id: "ASSE",
    color: "#ffeda0",
    neighbors: ['ASEA','ASSO','OCPL','OCMC'],
    description: ``,
    text: { x: 78, y: 48, el: <>Southeast<br/>Asia</>, },
    zoom: { x: 101, y: 51.3, amount: 3.5, },
  },
  {
    name: "Highland Asia",
    id: "ASHI",
    color: "#fb9a99",
    neighbors: ['ASSO','ASEA'],
    description: ``,
    text: { x: 71.3, y: 31, el: <>Highland<br/>Asia</>, },
    zoom: { x: 84, y: 31, amount: 5, },
  },
  {
    name: "South Asia",
    id: "ASSO",
    color: "#9970ab",
    neighbors: ['ASHI','ASWE'],
    description: ``,
    text: { x: 69, y: 38, el: <>South<br/>Asia</>, },
    zoom: { x: 84, y: 38.5, amount: 4, },
  },
  {
    name: "West Asia",
    id: "ASWE",
    color: "#80b1d2",
    neighbors: ['AFNO','ASSO','ASCE'],
    description: ``,
    text: { x: 61, y: 34, el: <>West<br/>Asia</>, },
    zoom: { x: 72.2, y: 34, amount: 4, },
  },
  {
    name: "Central Asia",
    id: "ASCE",
    color: "#7fcdbb",
    neighbors: ['ASIN','ASHI','ASWE','ASNO'],
    description: ``,
    text: { x: 64.6, y: 24.3, el: <>Central Asia</>, },
    zoom: { x: 79.3, y: 18.5, amount: 4.2, },
  },
  {
    name: "Inner Asia",
    id: "ASIN",
    color: "#ffeda4",
    neighbors: ['ASCE','ASHI','ASEA','ASNO'],
    description: ``,
    text: { x: 74.5, y: 22, el: <>Inner Asia</>, },
    zoom: { x: 91.5, y: 16.5, amount: 4.2, },
  },
  {
    name: "Eastern Europe",
    id: "EUEA",
    color: "#ffeda1",
    neighbors: ['EUWE','ASNO','ASWE','ASCE'],
    description: `This subregion is dominated by the Balto-Slavic and Uralic language families and the Balkan sprachbund.`,
    text: { x: 56.5, y: 16, el: <>Eastern<br/>Europe</>, },
    zoom: { x: 69, y: 6.5, amount: 3.5, },
  },
  {
    name: "Western Europe",
    id: "EUWE",
    color: "#fdbb85",
    description: `This subregion includes the Latin, Germanic, and Celtic cultural areas and the branches of the Indo-European language families of the same names.`,
    neighbors: ['EUEA','AFNO','ASWE'],
    text: { x: 48, y: 20, el: <>Western<br/>Europe</>, },
    zoom: { x: 57, y: 12.5, amount: 4, },
  },
  {
    name: "Australia",
    id: "OCAU",
    color: "#fdbb83",
    neighbors: ['OCML','ASSE'],
    description: ``,
    text: { x: 83.6, y: 73.5, el: <>Australia</>, },
    zoom: { x: 104, y: 85, amount: 4, },
  },
  {
    name: "Madagascar",
    id: "OCMD",
    color: "#fb9a97",
    neighbors: ['ASSE','AFEA','OCPL'],
    description: `A combination of Austronesian (originating in Maritime Southeast Asia) and later Bantu (via Southeast Africa) influences converge to constitute the Malagasy language and culture predominant across the island.`,
    text: { x: 61, y: 68, el: <>Madagascar</>, },
    zoom: { x: 70.5, y: 76, amount: 5, },
  },
  {
    name: "Melanesia",
    id: "OCML",
    color: "#fb9a98",
    neighbors: ['OCMC','OCAU','ASSE'],
    description: ``,
    shape: <path d="M 86,23.5 98,25 99.5,31 94.5,33 92,29 85,28 z" fill="#808080"></path>,
    text: { x: 87, y: 59, el: <>Melanesia</>, },
    zoom: { x: 113, y: 69, amount: 3.9, },
  },
  {
    name: "Micronesia",
    id: "OCMC",
    color: "#80b1d4",
    neighbors: ['OCPL','OCML','ASSE'],
    description: ``,
    shape: <path d="M 86,23.5 89,19 98,21 98,25 z" fill="#808080"></path>,
    text: { x: 90, y: 48, el: <>Micronesia</>, },
    zoom: { x: 110, y: 52, amount: 4.5, },
  },
  {
    name: "Polynesia",
    id: "OCPL",
    color: "#7fcdbc",
    neighbors: ['OCMC','OCML','ASSE'],
    description: ``,
    shape: <path d="M 88,42.5 100,40 100,23 98,25 99.5,31 94.5,33 z M 0,41 22,34.2 7.5,17 0,23 z" fill="#808080"></path>,
    text: { x: 3, y: 50, el: <>Polynesia</>, },
    zoom: { x: 2, y: 63, amount: 2.5, },
  },
];

export const getDesc = (id: string) => {
  let description = '';
  subregions.forEach(subr => {
    if ('description' in subr && id===subr.id) { description = subr.description; }
  }); return description;
};
