interface subregionType {
  name: string,
  id: string,
  color: string,
  shape?: React.ReactNode,
  neighbors: string[],
  description: string,
  text: {
    x: number,
    y: number,
    el: React.ReactNode,
  },
  zoom: {
    x: number,
    y: number,
    amount: number,
  },
}

export const subregions: subregionType[] = [
  {
    name: "North Africa",
    id: "AFNO",
    color: "#fb9a96",
    neighbors: ['EUWE','ASWE','AFWE'],
    description: `The Amazigh languages anchor the distinctive linguistic and cultural heritage of the Maghreb, Sahara, and Sahel.`,
    text: { x: 49.7, y: 39.2, el: <>North Africa</>, },
    zoom: { x: 62, y: 37, amount: 3.5, },
  },
  {
    name: "East Africa",
    id: "AFEA",
    color: "#fdbb86",
    neighbors: ['ASWE','AFNO','AFCE','OCMD'],
    description: `This subregion includes the Cushitic Horn of Africa, the Nilotic eastern Sudanian belt, the Bantu Swahili Coast, and the Hadza and Sandawe areas of the southeast.`,
    text: { x: 59, y: 50, el: <>East<br/>Africa</>, },
    zoom: { x: 74, y: 65, amount: 3, },
  },
  {
    name: "Southern Africa",
    id: "AFSO",
    color: "#9970ac",
    neighbors: ['AFEA','AFCE'],
    description: `Khoisan Southern Africa includes speakers of the click consonant Kxʼa, Taa–ǃKwi, and Khoe–Kwadi language families in the Karoo, Kalahari Basin, and Okavango Delta, in addition to click-borrowing Bantu groups like the Nguni.`,
    text: { x: 53.6, y: 69, el: <>Southern<br/>Africa</>, },
    zoom: { x: 66, y: 78, amount: 4, },
  },
  {
    name: "Central Africa",
    id: "AFCE",
    color: "#7fcdba",
    neighbors: ['AFWE','AFEA'],
    description: `Mbenga, Mbuti, and Twa groups in the Congo Basin speak the Bantu, Ubangian, and Central Sudanic languages of the surrounding areas, with some specialized botanical vocabulary of earlier origin.`,
    text: { x: 53.2, y: 54, el: <>Central<br/>Africa</>, },
    zoom: { x: 63, y: 59, amount: 4.5, },
  },
  {
    name: "West Africa",
    id: "AFWE",
    color: "#ffeda2",
    neighbors: ['AFNO','AFCE'],
    description: `Comprised of Upper and Lower Guinea (separated by the Dahomey Gap) and the western Sudanian savanna, this subregion is dominated by the western branches of the Niger–Congo language family.`,
    text: { x: 46.4, y: 48.3, el: <>West Africa</>, },
    zoom: { x: 56, y: 48.3, amount: 4, },
  },
  {
    name: "Northern North America",
    id: "AMNO",
    color: "#9970aa",
    neighbors: ['ASNO','AMNW','AMEA'],
    description: `The Eskaleut languages encircle the Arctic from Greenland to Alaska and extend across the Behring Strait to the Chukchi Peninsula, and are distinct from older Algic and Na-Dené parts of the Subarctic also in this subregion.`,
    text: { x: 23, y: 10, el: <>Northern N. Am.</>, },
    zoom: { x: 28, y: 0, amount: 2, },
  },
  {
    name: "Eastern North America",
    id: "AMEA",
    color: "#7fcdbd",
    neighbors: ['AMNO','AMIN','AMSW'],
    description: `Coterminous with the Eastern Woodlands, this subregion accounts for the cultural areas of the Northeastern and Southeastern Woodlands and the Great Lakes, including language families like the Algonquian, Iroquoian, and Muskogean.`,
    text: { x: 26.5, y: 27.5, el: <>Eastern<br/>N. Am.</>, },
    zoom: { x: 30, y: 22, amount: 4, },
  },
  {
    name: "Southwest North America",
    id: "AMSW",
    color: "#ffeda5",
    neighbors: ['AMCE','AMIN'],
    description: `Encompassing the American Southwest, Great Basin, and Californian cultural areas, where the Uto-Aztecan and Hokan families, alongside prominent isolates like Zuni and Washoe or outliers like Diné Bizaad, are spoken.`,
    text: { x: 17.8, y: 30.5, el: <>Southwest<br/>N. Am.</>, },
    zoom: { x: 19.5, y: 30.5, amount: 5, },
  },
  {
    name: "Northwest North America",
    id: "AMNW",
    color: "#80b1d5",
    neighbors: ['AMNO','AMIN'],
    description: `The Pacific Northwest Coast and Plateau cultural areas are largely defined by the diversity of Salishan, Penutian, Wakashan, Tsimshianic, and Chimakuan languages spread across the coast and interior.`,
    text: { x: 17, y: 17, el: <>Northwest<br/>N. Am.</>, },
    zoom: { x: 18, y: 16, amount: 5.5, },
  },
  {
    name: "Interior North America",
    id: "AMIN",
    color: "#fb9a93",
    neighbors: ['AMEA','AMNW','AMSW'],
    description: `The Interior Plains include the Great Plains, Canadian Prairies, and Rockies, having speakers of the Siouan, Caddoan, and Plains Algonquian language families.`,
    text: { x: 22.5, y: 21, el: <>Interior<br/>N. Am.</>, },
    zoom: { x: 24, y: 17, amount: 4.5, },
  },
  {
    name: "Central America",
    id: "AMCE",
    color: "#fdbb82",
    neighbors: ['AMSW','AMCR'],
    description: `Mesoamerica—the Nahua and Oto-Manguean spheres of influence in the east and the Mayan world in the west—as well as the transitional Isthmo-Colombian area's Chibchan and Misumalpan languages, constitute this subregion.`,
    text: { x: 21, y: 42, el: <>Central<br/>America</>, },
    zoom: { x: 23, y: 44, amount: 4.7, },
  },
  {
    name: "Caribbean",
    id: "AMCR",
    color: "#fb9a94",
    neighbors: ['AMLO','AMCE'],
    description: `This subregion includes the Arawakan Taíno languages of the Greater Antilles, and the more-recently introduced Cariban languages of the Lesser Antilles, alongside older languages like Guanahatabey, Macorix, and Ciguayo.`,
    text: { x: 28, y: 42, el: <>Caribbean</>, },
    zoom: { x: 30, y: 43, amount: 5.5, },
  },
  {
    name: "Highland South America",
    id: "AMHI",
    color: "#ffeda3",
    neighbors: ['AMLO','AMSO'],
    description: `The Andean Region is dominated by the imperial Quechuan and Aymaran languages, alongside families like the Chibchan and Barbacoan in the north, across the terrains of the Costeña, Cordillera, and eastern foothills.`,
    text: { x: 26, y: 61, el: <>Highland<br/>S. Am.</>, },
    zoom: { x: 29, y: 73.5, amount: 2.8, },
  },
  {
    name: "Lowland South America",
    id: "AMLO",
    color: "#80b1d1",
    neighbors: ['AMCR','AMSO','AMHI'],
    description: `The Guiana Shield, Orinoquia, Amazonia, and the Brazilian Plateau can all be found within this subregion, where the Macro-Jê, Tupian, Arawakan, Cariban, and Panoan languages, among others, are spoken.
`,
    text: { x: 32, y: 59, el: <>Lowland<br/>S. Am.</>, },
    zoom: { x: 36, y: 67, amount: 3.5, },
  },
  {
    name: "Southern South America",
    id: "AMSO",
    color: "#fb9a95",
    neighbors: ['AMLO','AMHI'],
    description: `The Southern Cone consists of Patagonia, the Pampas, the Southern Andes, and Tierra del Fuego, and includes language families like Araucanian and Tupí-Guaraní, and the Chon and Puelche-Het of the Fuegian sprachbund.`,
    text: { x: 32, y: 79, el: <>Southern<br/>S. Am.</>, },
    zoom: { x: 36, y: 96.5, amount: 3.7, },
  },
  {
    name: "North Asia",
    id: "ASNO",
    color: "#80b1d3",
    neighbors: ['AMNO','EUEA','ASIN','ASCE'],
    description: `Siberia, its peninsulas from the Yamal to the Kamchatka and islands like Sakhalin and Hokkaido, contains speakers of Uralic and Tungusic languages and older families like Chukotko–Kamchatkan, Nivkh, Yeniseian, and Yukaghir.`,
    text: { x: 71, y: 11.2, el: <>North Asia</>, },
    zoom: { x: 110, y: 5, amount: 2.25, },
  },
  {
    name: "East Asia",
    id: "ASEA",
    color: "#fdbb84",
    neighbors: ['ASIN','ASHI','ASSE'],
    description: `The Sinitic, Koreanic, and Japonic languages form the core of this sphere of cultural interchange surrounding the East China Sea.`,
    text: { x: 79, y: 34, el: <>East Asia</>, },
    zoom: { x: 96.5, y: 30, amount: 4, },
  },
  {
    name: "Southeast Asia",
    id: "ASSE",
    color: "#ffeda0",
    neighbors: ['ASEA','ASSO','OCPL','OCMC'],
    description: `Southeast Asia is most clearly divided into its Mainland and Maritime components, where Austroasiatic, Kra–Dai, and Sino–Tibetan areas dominate the Indochinese sprachbund in the former, and Austronesian features extend throughout the Malaysphere in the latter.`,
    text: { x: 78, y: 48, el: <>Southeast<br/>Asia</>, },
    zoom: { x: 101, y: 51.25, amount: 3.4, },
  },
  {
    name: "Highland Asia",
    id: "ASHI",
    color: "#fb9a99",
    neighbors: ['ASSO','ASEA'],
    description: `This subregion is characterized by the Tibetic sphere of influence pervading the Qinghai-Tibetan Plateau and the Himalayas, including the central Ü-Tsang, eastern Kham, and northeastern Amdo regional groupings.`,
    text: { x: 71.3, y: 31, el: <>Highland<br/>Asia</>, },
    zoom: { x: 84, y: 31, amount: 5, },
  },
  {
    name: "South Asia",
    id: "ASSO",
    color: "#9970ab",
    neighbors: ['ASHI','ASWE'],
    description: `The Dravidian languages in the south, as well as the Indo-Aryan languages of the Indus-Gangetic Plain in the north and Iranian-influenced northwest, comprise the major linguistic and cultural areas of this subregion.`,
    text: { x: 69, y: 38, el: <>South<br/>Asia</>, },
    zoom: { x: 84, y: 38.5, amount: 4, },
  },
  {
    name: "West Asia",
    id: "ASWE",
    color: "#80b1d2",
    neighbors: ['AFNO','ASSO','ASCE'],
    description: `The Arabian Peninsula, Iranian Plateau, and Anatolia comprise the Arabic, Persic, and Turkic spheres of this subregion, in addition to transitional areas like Mesopotamia, Sinai, and the Armenian Highlands.`,
    text: { x: 61, y: 34, el: <>West<br/>Asia</>, },
    zoom: { x: 72.2, y: 34, amount: 4, },
  },
  {
    name: "Central Asia",
    id: "ASCE",
    color: "#7fcdbb",
    neighbors: ['ASIN','ASHI','ASWE','ASNO'],
    description: `The central Eurasian Steppe, stretching from the Ural mountains in the west to the Altai mountains in the east, is predominantly a diverse mix of Turkic and Iranic cultures.`,
    text: { x: 64.6, y: 24.3, el: <>Central Asia</>, },
    zoom: { x: 79.3, y: 18.5, amount: 4.2, },
  },
  {
    name: "Inner Asia",
    id: "ASIN",
    color: "#ffeda4",
    neighbors: ['ASCE','ASHI','ASEA','ASNO'],
    description: `The cultural and linguistic domains of the Mongolic and southern Tungusic peoples extend across the eastern Eurasian Steppe and Manchuria in this subregion.`,
    text: { x: 74.5, y: 22, el: <>Inner Asia</>, },
    zoom: { x: 91.5, y: 16.5, amount: 4.2, },
  },
  {
    name: "Eastern Europe",
    id: "EUEA",
    color: "#ffeda1",
    neighbors: ['EUWE','ASNO','ASWE','ASCE'],
    description: `This subregion is dominated by the Balto-Slavic and Uralic language families and the Balkan sprachbund; its extensive plains are bordered by the Carpathian, Ural, and Caucasus mountain ranges to the west, east, and south.`,
    text: { x: 56.5, y: 16, el: <>Eastern<br/>Europe</>, },
    zoom: { x: 69, y: 6.5, amount: 3.5, },
  },
  {
    name: "Western Europe",
    id: "EUWE",
    color: "#fdbb85",
    description: `This subregion includes the Latin, Germanic, and Celtic cultural areas, in various admixtures, and the branches of the Indo-European language families of the same names.`,
    neighbors: ['EUEA','AFNO','ASWE'],
    text: { x: 48, y: 20, el: <>Western<br/>Europe</>, },
    zoom: { x: 57, y: 12.5, amount: 4, },
  },
  {
    name: "Australia",
    id: "OCAU",
    color: "#fdbb83",
    neighbors: ['OCML','ASSE'],
    description: `The Pama–Nyungan language family, of which three-quarters of all Australian languages are part, covers nearly 90% of the continent, while the remaining 23-30 families and isolates are clustered in the north.`,
    text: { x: 83.6, y: 73.5, el: <>Australia</>, },
    zoom: { x: 104, y: 85, amount: 4, },
  },
  {
    name: "Madagascar",
    id: "OCMD",
    color: "#fb9a97",
    neighbors: ['ASSE','AFEA','OCPL'],
    description: `A combination of Austronesian (originating in Maritime Southeast Asia) and later Bantu (via Southeast Africa) influences converge to constitute the Malagasy language and culture predominant across the island.`,
    text: { x: 61, y: 68, el: <>Madagascar</>, },
    zoom: { x: 70.5, y: 76, amount: 5, },
  },
  {
    name: "Melanesia",
    id: "OCML",
    color: "#fb9a98",
    neighbors: ['OCMC','OCAU','ASSE'],
    description: `There are 1,000–1,500 distinct languages spoken in Melanesia, as much as one-quarter of the global total, centered on New Guinea and the surrounding islands, with Austronesian languages in some coastal areas.`,
    shape: <path d="M 86,23.5 98,25 99.5,31 94.5,33 92,29 85,28 z" fill="#808080"></path>,
    text: { x: 87, y: 59, el: <>Melanesia</>, },
    zoom: { x: 112.7, y: 69, amount: 3.9, },
  },
  {
    name: "Micronesia",
    id: "OCMC",
    color: "#80b1d4",
    neighbors: ['OCPL','OCML','ASSE'],
    description: `Austronesian languages of the Oceanic branch pervade throughout this subregion, where extensive maritime vocabulary and a unique synthesis of Melanesian and Polynesian influences dominate.`,
    shape: <path d="M 86,23.5 89,19 98,21 98,25 z" fill="#808080"></path>,
    text: { x: 90, y: 48, el: <>Micronesia</>, },
    zoom: { x: 110, y: 52, amount: 4.5, },
  },
  {
    name: "Polynesia",
    id: "OCPL",
    color: "#7fcdbc",
    neighbors: ['OCMC','ASSE','OCML'],
    description: `Speakers of the closely related Polynesian languages of the Oceanic branch of Austronesian span the vast expanse of ocean covered by the Polynesian Triangle.`,
    shape: <path d="M 88,42.5 100,40 100,23 98,25 99.5,31 94.5,33 z M 0,41 22,34.2 7.5,17 0,23 z" fill="#808080"></path>,
    text: { x: 3, y: 50, el: <>Polynesia</>, },
    zoom: { x: 2, y: 63, amount: 2.5, },
  },
];

export const getDesc = (id: string) => {
  let description = '';
  subregions.forEach(subr => {
    if ('description' in subr && id===subr.id) { description = subr.description; }
  }); return description;
};
